// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {Choice} from './Choice';
import type {Next} from './Next';

export interface Event {
  text: string;
  next: Array<Next> | null;
  effects: Record<string, boolean> | null;
  choices: Array<Choice> | null;
}

export enum EventOutcomeType {
  NONE,
  CHOICES,
  EVENTS,
}

export function getEventOutcomeType(e: Event): EventOutcomeType {
  if (e.choices && e.choices.length > 0) {
    return EventOutcomeType.CHOICES;
  }
  // TODO the original model could be perfected here.. since an event can only have one and only Outcome type
  if (e.next && e.next.length > 0) {
    return EventOutcomeType.EVENTS;
  }
  return EventOutcomeType.NONE;
}
